export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST= 'LOGOUT_REQUEST';

export const START_LOGIN = 'START_LOGIN';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SAVE_TOKEN_LOGIN = 'SAVE_TOKEN_LOGIN';
export const REMOVE_TOKEN_LOGIN = 'REMOVE_TOKEN_LOGIN';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';