export const ADD_CART = 'ADD_CART';

export const START_ADD_CART = 'START_ADD_CART';
export const FINISH_ADD_CART = 'FINISH_ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const DELETE_ITEM_CART = 'DELETE_ITEM_CART';
export const CHANGE_QTY_CART = 'CHANGE_QTY_CART';